services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./main.py:/app/main.py
            - ./app:/app/app
        networks:
            - proxy
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.pdf-converter.rule=Host(`pdf-converter.ninebit.test`)'
            - 'traefik.http.routers.pdf-converter.entrypoints=websecure'
            - 'traefik.http.routers.pdf-converter.tls=true'
            - 'traefik.http.services.pdf-converter.loadbalancer.server.port=8000'
            - 'traefik.docker.network=proxy'

networks:
    proxy:
        external: true
